version: '3.9'

services:
  nestapp:
    container_name: nestapp
    image: arisallka/nestapp:1.0.0
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USERNAME=postgres
      - PG_PASSWORD=password
      - PG_DB=postgres
      - PG_PORT=5432
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
